"""fix_agents_created_at_default

Revision ID: aaca07b20ea9
Revises: f79da474c69d
Create Date: 2026-02-01 01:11:12.645015

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaca07b20ea9"
down_revision: Union[str, None] = "f79da474c69d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index on agents.id if it doesn't exist
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    indexes = inspector.get_indexes("agents")
    if not any(index["name"] == "ix_agents_id" for index in indexes):
        op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index on agents.id
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    indexes = inspector.get_indexes("agents")
    if any(index["name"] == "ix_agents_id" for index in indexes):
        op.drop_index(op.f("ix_agents_id"), table_name="agents")
    # ### end Alembic commands ###
