"""add user_oauth table

Revision ID: c7dfa28cc67a
Revises: 44a6d3a54c35
Create Date: 2026-03-13 12:53:59.677483

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7dfa28cc67a"
down_revision: Union[str, None] = "44a6d3a54c35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_type", sa.String(length=50), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("provider_user_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", "provider_user_id", name="uq_user_provider_account"
        ),
    )
    op.create_index(op.f("ix_user_oauth_id"), "user_oauth", ["id"], unique=False)

    # SQLite workaround for altering columns and constraints
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_index("ix_uploaded_files_file_id")
        batch_op.create_index(
            batch_op.f("ix_uploaded_files_file_id"), ["file_id"], unique=True
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_uploaded_files_storage_path"), ["storage_path"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_uploaded_files_storage_path"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_uploaded_files_file_id"))
        batch_op.create_index("ix_uploaded_files_file_id", ["file_id"], unique=False)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    op.drop_index(op.f("ix_user_oauth_id"), table_name="user_oauth")
    op.drop_table("user_oauth")
    # ### end Alembic commands ###
